filmsite/genres/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField

class AddForm(FlaskForm):
    name = StringField('Naam genre:')
    submit = SubmitField('Opslaan')

class DelForm(FlaskForm):
    submit = SubmitField('Verwijder')

filmsite/genres/views.py
from flask import Blueprint, render_template, redirect, url_for
from filmsite import db, flash, login_required
from filmsite.genres.forms import AddForm, DelForm
from filmsite.models import Movie, Director, Actor, Role, Genre

genres_blueprint = Blueprint('genres',
                               __name__,
                               template_folder='templates')

@genres_blueprint.route('/list')
def list():
    genres = Genre.query.all()
    return render_template('genres/all.html', genres=genres)


@genres_blueprint.route('/add', methods=['GET', 'POST'])
@login_required
def add():
    form = AddForm()

    if form.validate_on_submit():
        name = form.name.data
        new_genre = Genre(name=name)

        db.session.add(new_genre)
        db.session.commit()

        flash("Nieuwe genre succesvol toegevoegd.")

        return redirect(url_for('genres.list'))
    return render_template('genres/create.html', form=form)


@genres_blueprint.route('/<genre_id>')
def show(genre_id):
    genre = Genre.query.filter_by(id=genre_id).first()
    movies_in_genre = [movie.movie_id for movie in genre.movies]
    movies = Movie.query.all()
    return render_template('genres/view.html', genre=genre, movies = movies, movies_in_genre=movies_in_genre)



@genres_blueprint.route('/<genre_id>/edit', methods=['GET', 'POST'])
@login_required
def edit(genre_id):
    genre = Genre.query.filter_by(id=genre_id).first()
    form = AddForm(obj=genre)

    if form.validate_on_submit():
        genre.name=form.name.data

        db.session.add(genre)
        db.session.commit()

        flash("Genre succesvol bewerkt.")

        return redirect(url_for('genres.list'))
    return render_template('genres/edit.html', form=form)


@genres_blueprint.route('/<genre_id>/delete', methods=['GET', 'POST'])
@login_required
def delete(genre_id):

    genre = Genre.query.filter_by(id=genre_id).first()
    form = DelForm(obj=genre)

    if form.validate_on_submit():
        db.session.delete(genre)
        db.session.commit()

        flash("Genre succesvol verwijderd.")

        return redirect(url_for('genres.list'))
    return render_template("genres/delete.html", form=form, genre=genre)

filmsite/genres/templates/genres/all.html
{% extends "base.html" %}

{% block page_name %}Alle directeurs{% endblock %}

{% block page %}

{% if current_user.is_authenticated %}
<a class="btn btn-primary" href="{{ url_for('genres.add') }}">
    Maak nieuwe genre aan
</a>
{% endif %}

{% for genre in genres %}
<a href="{{ url_for('genres.show', genre_id = genre.id) }}">
    <h3>
        {{ genre.name }}
    </h3>
</a>

{% endfor %}

{% endblock %}

filmsite/genres/templates/genres/create.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block page_name %} Maak nieuwe genre aan {% endblock %}
{% block page %}

    <h1>Maak genre aan</h1>
    {{ wtf.quick_form(form, button_map={'submit': 'primary'}) }}

{% endblock %}

filmsite/genres/templates/genres/delete.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_name %}Verwijder genre{% endblock %}

{% block page %}
<h3>Weet je zeker dat je deze genre wilt verwijderen?</h3>

{{ wtf.quick_form(form, button_map={'submit': 'danger'}) }}
{% endblock %}

filmsite/genres/templates/genres/edit.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block page_name %} Bewerk genre {% endblock %}
{% block page %}

    <h1>Bewerk genre</h1>
    {{ wtf.quick_form(form, button_map={'submit': 'primary'}) }}

{% endblock %}

filmsite/genres/templates/genres/view.html
{% extends "base.html" %}

{% block page_name %} Genre {{ genre.name }}{% endblock %}

{% block page %}

{% if current_user.is_authenticated %}
<a class="btn btn-primary" href="{{ url_for('genres.edit', genre_id = genre.id) }}">
    Bewerk genre
</a>

<a class="btn btn-danger" href="{{url_for('genres.delete', genre_id = genre.id)}}">Verwijder genre</a>
{% endif %}
<h3>
    {{ genre.name }}
</h3>

<h4>
    Films in genre:
</h4>
<ul>
    {% for movie in movies %}
    {% if movie.id in movies_in_genre %}
    <li>
        Regisseur van <a href="{{ url_for('movies.show', movie_id = movie.id) }}">{{movie.title}}</a>
            
    </li>
    {% endif %}
    {% endfor %}
</ul>

{% endblock %}