filmsite/actors/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField

class AddForm(FlaskForm):
    first_name = StringField('Voornaam acteur:')
    last_name = StringField('Achternaam acteur:')
    submit = SubmitField('Opslaan')

class DelForm(FlaskForm):
    submit = SubmitField('Verwijder')

filmsite/actors/views.py
from flask import Blueprint, render_template, redirect, url_for
from filmsite import db, flash, login_required
from filmsite.models import Actor
from filmsite.actors.forms import AddForm, DelForm

actors_blueprint = Blueprint('actors',
                                __name__,
                                template_folder='templates/actors')


@actors_blueprint.route('/list')
def list():
    actors = Actor.query.all()
    return render_template('all.html', actors=actors)


@actors_blueprint.route('/add', methods=['GET', 'POST'])
@login_required
def add():

    form = AddForm()

    if form.validate_on_submit():
        first_name = form.first_name.data
        last_name = form.last_name.data
        new_actor = Actor(first_name=first_name, last_name=last_name)

        db.session.add(new_actor)
        db.session.commit()

        flash("Nieuwe acteur succesvol toegevoegd.")

        return redirect(url_for('actors.list'))
    return render_template('create.html', form=form)


@actors_blueprint.route("/<actor_id>", methods=['GET', 'POST'])
def show(actor_id):
    actor = Actor.query.filter_by(id=actor_id).first()

    return render_template("view.html", actor=actor)



@actors_blueprint.route("/<actor_id>/edit", methods=['GET', 'POST'])
@login_required
def edit(actor_id):
    actor = Actor.query.filter_by(id=actor_id).first()
    form = AddForm(obj=actor)

    if form.validate_on_submit():

        actor.first_name = form.first_name.data
        actor.last_name = form.last_name.data


        db.session.add(actor)
        db.session.commit()

        flash("Acteur succesvol bijgewerkt.")
        return redirect(url_for('actors.show', actor_id = actor.id))

    return render_template("edit.html", form=form, actor=actor)


@actors_blueprint.route('/<actor_id>/delete', methods=['GET', 'POST'])
@login_required
def delete(actor_id):

    actor = Actor.query.filter_by(id=actor_id).first()
    form = DelForm(obj=actor)

    if form.validate_on_submit():
        db.session.delete(actor)
        db.session.commit()

        flash("Acteur succesvol verwijderd.")

        return redirect(url_for('actors.list'))
    return render_template("delete.html", form=form, actor=actor)

filmsite/actors/templates/actors/all.html
{% extends "base.html" %}

{% block page_name %}Alle acteurs{% endblock %}

{% block page %}

{% if current_user.is_authenticated %}
<a class="btn btn-primary" href="{{ url_for('actors.add') }}">
    Maak nieuwe acteur aan
</a>
{% endif %}

{% for actor in actors %}
<a href="{{ url_for('actors.show', actor_id = actor.id) }}">
    <h3>
        {{ actor.first_name }} {{ actor.last_name}}
    </h3>
</a>

{% endfor %}

{% endblock %}

filmsite/actors/templates/actors/create.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block page_name %} Maak nieuwe acteur aan {% endblock %}
{% block page %}

    <h1>Voeg acteur toe</h1>
    {{ wtf.quick_form(form, button_map={'submit': 'primary'}) }}

{% endblock %}

filmsite/actors/templates/actors/delete.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_name %}Verwijder acteur{% endblock %}

{% block page %}
<h3>Weet je zeker dat je deze acteur wilt verwijderen?</h3>

{{ wtf.quick_form(form, button_map={'submit': 'danger'}) }}
{% endblock %}

filmsite/actors/templates/actors/edit.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block page_name %} Maak nieuwe acteur aan {% endblock %}
{% block page %}

    <h1>Bewerk acteur</h1>
    {{ wtf.quick_form(form, button_map={'submit': 'primary'}) }}

{% endblock %}

filmsite/actors/templates/actors/view.html
{% extends "base.html" %}

{% block page_name %} Acteur {{actor.first_name}} {{ actor.last_name}}{% endblock %}

{% block page %}

{% if current_user.is_authenticated %}
<a class="btn btn-primary" href="{{ url_for('actors.edit', actor_id = actor.id) }}">
    Bewerk acteur
</a>

<a class="btn btn-danger" href="{{url_for('actors.delete', actor_id = actor.id)}}">Verwijder acteur</a>
{% endif %}
<h3>
    {{ actor.first_name }} {{ actor.last_name}}
</h3>

<h4>
    Rollen:
</h4>
<ul>
    {% for role in actor.roles %}
    {% if role.movie_id %}
    <li>
        {{role.playing_as}} in <a href="{{ url_for('movies.show', movie_id = role.movies.id) }}">{{role.movies.title}}</a>
            
    </li>
    {% endif %}
    {% endfor %}
</ul>

{% endblock %}