filmsite/movies/forms.py
from flask_wtf import FlaskForm
import wtforms
from wtforms.validators import DataRequired, Length, EqualTo
from wtforms import StringField, IntegerField, SubmitField, widgets, SelectMultipleField
from filmsite.models import Director

class DelForm(FlaskForm):
    submit = SubmitField('Verwijder')

class MultiCheckboxField(SelectMultipleField):
    widget = widgets.ListWidget(prefix_label=False)
    option_widget = widgets.CheckboxInput()

class CreateForm(FlaskForm):
    title = wtforms.StringField(
        "Titel film",
        validators=[DataRequired()],
        render_kw={'placeholder': 'Titel...'}
    )

    release_year = wtforms.IntegerField(
        "Jaar van uitgave", validators=[DataRequired()],
        render_kw={'placeholder': 'Jaar...'}
    )

    visitor_amount = wtforms.IntegerField(
        "Aantal bezoekers", validators=[DataRequired()],
        render_kw={'placeholder': 'Aantal...'}
    )

    gross_income = wtforms.IntegerField(
        "Opbrengst", validators=[DataRequired()],
        render_kw={'placeholder': 'Opbrengst...'}
    )

    playtime = wtforms.IntegerField(
        "Speelduur", validators=[DataRequired()],
        render_kw={'placeholder': 'Lengte...'}
    )

    trailer_url = wtforms.StringField(
        "Trailer url (youtube link)", validators=[DataRequired()],
        render_kw={'placeholder': 'Url...'}
    )

    director_id = wtforms.SelectField(
        "Kies een regisseur", validators=[DataRequired()], coerce=int
    )

    genres = MultiCheckboxField('Kies genres', coerce=int)

    submit = wtforms.SubmitField("Opslaan")
    

filmsite/movies/views.py
from flask import Blueprint, render_template, redirect, url_for
from filmsite import db, flash, login_required
from filmsite.movies.forms import CreateForm, DelForm
from filmsite.roles.forms import RoleForm, DelRoleForm
from filmsite.models import Movie, Director, Actor, Role, Genre, MovieGenres

movies_blueprint = Blueprint('movies',
                               __name__,
                               template_folder='templates')


def render(name, form):
    url = 'movies/'
    return render_template(url + name + '.html', form=form)


@movies_blueprint.route('/add', methods=['GET', 'POST'])
@login_required
def add():
    form = CreateForm()

    directors = Director.query.all()
    directors_list=[(i.id, i.first_name + ' ' + i.last_name) for i in directors]
    form.director_id.choices = directors_list

    genres = Genre.query.all()
    genres_list=[(i.id, i.name) for i in genres]
    form.genres.choices = genres_list

    if form.validate_on_submit():
    
        new_movie = Movie(
            title=form.title.data, 
            release_year=form.release_year.data, 
            visitor_amount = form.visitor_amount.data,
            gross_income = form.gross_income.data,
            playtime = form.playtime.data,
            trailer_url = form.trailer_url.data,
            director_id = form.director_id.data
            )

        db.session.add(new_movie)
        db.session.commit()

        for genre in form.genres.data:
            new_genre = MovieGenres(
                movie_id=movie.id, 
                genre_id=genre)
            db.session.add(new_genre)

        flash("Nieuwe film succesvol toegevoegd.")
        return redirect(url_for('movies.show', movie_id = new_movie.id))
    return render('create', form)


@movies_blueprint.route('/list')
def list():
    movies = Movie.query.all()
    return render_template('movies/all.html', movies=movies)


@movies_blueprint.route('/<movie_id>/delete', methods=['GET', 'POST'])
@login_required
def delete(movie_id):

    movie = Movie.query.filter_by(id=movie_id).first()
    form = DelForm(obj=movie)

    if form.validate_on_submit():
        db.session.delete(movie)
        db.session.commit()

        flash("Film succesvol verwijderd.")

        return redirect(url_for('movies.list'))
    return render('delete', form)



@movies_blueprint.route("/<movie_id>", methods=['GET', 'POST'])
def show(movie_id):
    movie = Movie.query.filter_by(id=movie_id).first()

    return render_template("movies/view.html", movie=movie)


@movies_blueprint.route("/<movie_id>/add_role", methods=['GET', 'POST'])
@login_required
def add_role(movie_id):
    movie = Movie.query.filter_by(id=movie_id).first()
    form = RoleForm()

    actors = Actor.query.all()
    actors_list=[]
    for actor in actors:
        if movie.id not in [role.movie_id for role in actor.roles]:
            actors_list.append((actor.id, actor))
    form.actor_id.choices = actors_list

    if form.validate_on_submit():

        new_role = Role(
            movie_id=movie.id, 
            actor_id=form.actor_id.data, 
            playing_as = form.playing_as.data)

        db.session.add(new_role)
        db.session.commit()

        flash("Nieuwe rol succesvol toegevoegd.")
        return redirect(url_for('movies.show', movie_id = movie.id))

    return render_template("movies/add_role.html", form=form, movie=movie)

@movies_blueprint.route("/<movie_id>/edit_role/<role_id>", methods=['GET', 'POST'])
@login_required
def edit_role(movie_id, role_id):
    movie = Movie.query.filter_by(id=movie_id).first()
    role = Role.query.filter_by(id=role_id).first()
    form = RoleForm(obj=role)

    actors = Actor.query.all()
    actors_list=[]
    for actor in actors:
        if movie.id not in [role.movie_id for role in actor.roles] or role.actor_id == actor.id:
            actors_list.append((actor.id, actor))
    form.actor_id.choices = actors_list

    if form.validate_on_submit():

        role.movie_id=movie.id, 
        role.actor_id=form.actor_id.data, 
        role.playing_as = form.playing_as.data

        db.session.add(role)
        db.session.commit()

        flash("Rol succesvol bewerkt.")
        return redirect(url_for('movies.show', movie_id = movie.id))

    return render_template("movies/edit_role.html", form=form, movie=movie, role=role)



@movies_blueprint.route('/<movie_id>/delete_role/<role_id>', methods=['GET', 'POST'])
@login_required
def delete_role(movie_id, role_id):

    role = Role.query.filter_by(id=role_id).first()
    form = DelRoleForm(obj=role)

    if form.validate_on_submit():
        db.session.delete(role)
        db.session.commit()

        flash("Rol succesvol verwijderd.")

        return redirect(url_for('movies.show', movie_id = movie_id))
    return render('delete_role', form)


@movies_blueprint.route("/<movie_id>/edit", methods=['GET', 'POST'])
@login_required
def edit(movie_id):
    movie = Movie.query.filter_by(id=movie_id).first()
    form = CreateForm(obj=movie)

    directors = Director.query.all()
    directors_list=[(i.id, i.first_name + ' ' + i.last_name) for i in directors]
    form.director_id.choices = directors_list

    genres = Genre.query.all()
    genres_list=[(i.id, i.name) for i in genres]
    form.genres.choices = genres_list

    if form.validate_on_submit():

        movie.title = form.title.data
        movie.release_year = form.release_year.data
        movie.director_id = form.director_id.data
        movie.visitor_amount = form.visitor_amount.data
        movie.gross_income = form.gross_income.data
        movie.playtime = form.playtime.data
        movie.trailer_url = form.trailer_url.data

        for genre in movie.genres:
            if genre not in form.genres.data:
                movie_genre = MovieGenres.query.filter_by(id=genre.id).first()
                db.session.delete(movie_genre)
        db.session.commit()

        for genre in form.genres.data:
            new_genre = MovieGenres(
                movie_id=movie.id, 
                genre_id=genre)
            db.session.add(new_genre)
        db.session.commit()


        db.session.add(movie)
        db.session.commit()

        flash("Film succesvol bijgewerkt.")
        return redirect(url_for('movies.show', movie_id = movie.id))

    return render_template("movies/edit.html", form=form, movie=movie, genres=movie.genres)

filmsite/movies/templates/movies/add_role.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_name %}Voeg rol toe{% endblock %}

{% block page %}
<div>
    <h1>Voeg rol toe aan de film {{ movie.title }}</h1>
    {% if error %}
        <p class=error><strong>Error:</strong> {{ error }}</p>
    {% endif %}
    {{ wtf.quick_form(form, button_map={'submit': 'primary btn-large'}) }}

</div>
{% endblock %}

filmsite/movies/templates/movies/all.html
{% extends "base.html" %}

{% block page_name %}Alle films{% endblock %}

{% block page %}

{% if current_user.is_authenticated %}
<a class="btn btn-primary" href="{{ url_for('movies.add') }}">
    Maak nieuwe film aan
</a>
{% endif %}

{% for movie in movies %}
<a href="{{ url_for('movies.show', movie_id = movie.id) }}">
    <h3>
        {{ movie.title }}
    </h3>
    <p class="text-info">
        Jaar van uitkomst: {{movie.release_year}}
    </p>
</a>

{% endfor %}

{% endblock %}

filmsite/movies/templates/movies/create.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_name %}Maak film aan{% endblock %}

{% block page %}
<div>
    <h1>Maak film aan</h1>
    {% if error %}
        <p class=error><strong>Error:</strong> {{ error }}</p>
    {% endif %}
    {{ wtf.quick_form(form, button_map={'submit': 'primary btn-large'}) }}

</div>
{% endblock %}

filmsite/movies/templates/movies/delete.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_name %}Verwijder film{% endblock %}

{% block page %}
<h3>Weet je zeker dat je deze film wilt verwijderen?</h3>

{{ wtf.quick_form(form, button_map={'submit': 'danger'}) }}
{% endblock %}

filmsite/movies/templates/movies/delete_role.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_name %}Verwijder film{% endblock %}

{% block page %}
<h3>Weet je zeker dat je deze rol wilt verwijderen?</h3>

{{ wtf.quick_form(form, button_map={'submit': 'danger'}) }}
{% endblock %}

filmsite/movies/templates/movies/edit.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_name %}Bewerk film{% endblock %}

{% block page %}
<div>
    <h1>Bewerk film</h1>
    {% if error %}
        <p class=error><strong>Error:</strong> {{ error }}</p>
    {% endif %}
    <div id="checked_genres" style="display: none;">{% for genre in genres %}{{genre.genre_id}} {% endfor %}</div>
    {{ wtf.quick_form(form, button_map={'submit': 'primary'}) }}

</div>
{% endblock %}

filmsite/movies/templates/movies/edit_role.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_name %}Voeg rol toe{% endblock %}

{% block page %}
<div>
    <h1>Voeg rol toe aan de film {{ movie.title }}</h1>
    {% if error %}
        <p class=error><strong>Error:</strong> {{ error }}</p>
    {% endif %}
    {{ wtf.quick_form(form, button_map={'submit': 'primary btn-large'}) }}

    <br>
    <a class="btn btn-danger" href="{{url_for('movies.delete_role', movie_id = movie.id, role_id = role.id)}}">Verwijder rol</a>

</div>
{% endblock %}

filmsite/movies/templates/movies/view.html
{% extends "base.html" %}

{% block page_name %}{{movie.title}}{% endblock %}

{% block page %}

{% if current_user.is_authenticated %}
<a class="btn btn-primary" href="{{ url_for('movies.edit', movie_id = movie.id) }}">
    Bewerk film
</a>
<a class="btn btn-primary" href="{{ url_for('movies.add_role', movie_id = movie.id) }}">
    Voeg rol toe
</a>
<a class="btn btn-danger" href="{{url_for('movies.delete', movie_id = movie.id)}}">Verwijder film</a>
{% endif %}

<div class="row">
    <div class="col col-md-6 col-lg-4">


        <h3>
            {{ movie.title }}
        </h3>
        <p class="text-info">
            Jaar van uitkomst: {{movie.release_year}}
        </p>
        <p class="text-info">
            Regisseur:
            <a href="{{url_for('directors.show', director_id = movie.directors.id)}}">
                {{movie.directors}}
            </a>
        </p>

        <p class="text-info">
            Aantal bezoekers: {{'{:,}'.format(movie.visitor_amount).replace(',','.')}}
        </p>

        <p class="text-info">
            Opbrengst: € {{'{:,}'.format(movie.gross_income).replace(',','.')}}
        </p>

        <p class="text-info">
            Speelduur: {{movie.playtime}} minuten
        </p>

        <p class="text-info">
        <h4>
            Genres:
        </h4>
        <ul>

            {% for genre in movie.genres %}
            {% if genre.genres.name %}
            <li>
                <a href="{{url_for('genres.show', genre_id = genre.genres.id)}}">
                    {{genre.genres.name}}
                </a>
            </li>
            {% endif %}
            {% endfor %}
        </ul>
        </p>

        {% if movie.roles %}
        <h4>Rollen</h4>
        {% for role in movie.roles %}
        {% if role.actor_id %}
        <p>
            <a href="{{ url_for('actors.show', actor_id = role.actors.id)}}">
                {{role.actors}}</a>
            als
            {{role.playing_as}}
            {% if current_user.is_authenticated %}
            <a href="{{ url_for('movies.edit_role', movie_id = movie.id, role_id = role.id) }}">
                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
            </a>
            {% endif %}
        </p>
        {% endif %}
        {% endfor %}
        {% endif %}

    </div>
    <div class="col col-md-6 col-lg-8">

        <p class="text-info">
        <div class="embed-responsive embed-responsive-16by9">
            <iframe class="embed-responsive-item" width="560" height="315"
                src="https://www.youtube.com/embed/{{movie.trailer_url.split('/')[-1]}}" title="YouTube video player"
                frameborder="0"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                allowfullscreen></iframe>
        </div>

        </p>

    </div>
</div>

{% endblock %}