filmsite/directors/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField

class AddForm(FlaskForm):
    first_name = StringField('Voornaam regisseur:')
    last_name = StringField('Achternaam regisseur:')
    submit = SubmitField('Opslaan')

class DelForm(FlaskForm):
    submit = SubmitField('Verwijder')

filmsite/directors/views.py
from flask import Blueprint, render_template, redirect, url_for
from filmsite import db, flash, login_required
from filmsite.models import Director
from filmsite.directors.forms import AddForm, DelForm

directors_blueprint = Blueprint('directors',
                                __name__,
                                template_folder='templates')

url = 'directors/'

@directors_blueprint.route('/list')
def list():
    directors = Director.query.all()
    return render_template(url + 'all.html', directors=directors)


@directors_blueprint.route('/add', methods=['GET', 'POST'])
@login_required
def add():

    form = AddForm()

    if form.validate_on_submit():
        first_name = form.first_name.data
        last_name = form.last_name.data
        new_director = Director(first_name=first_name, last_name=last_name)

        db.session.add(new_director)
        db.session.commit()

        flash("Nieuwe regisseur succesvol toegevoegd.")

        return redirect(url_for('directors.list'))
    return render_template(url + 'create.html', form=form)


@directors_blueprint.route("/<director_id>", methods=['GET', 'POST'])
def show(director_id):
    director = Director.query.filter_by(id=director_id).first()

    return render_template(url + "view.html", director=director)



@directors_blueprint.route("/<director_id>/edit", methods=['GET', 'POST'])
@login_required
def edit(director_id):
    director = Director.query.filter_by(id=director_id).first()
    form = AddForm(obj=director)

    if form.validate_on_submit():

        director.first_name = form.first_name.data
        director.last_name = form.last_name.data


        db.session.add(director)
        db.session.commit()

        flash("Regisseur succesvol bijgewerkt.")
        return redirect(url_for('directors.show', director_id = director.id))

    return render_template(url + "edit.html", form=form, director=director)


@directors_blueprint.route('/<director_id>/delete', methods=['GET', 'POST'])
@login_required
def delete(director_id):

    director = Director.query.filter_by(id=director_id).first()
    form = DelForm(obj=director)

    if form.validate_on_submit():
        db.session.delete(director)
        db.session.commit()

        flash("Regisseur succesvol verwijderd.")

        return redirect(url_for('directors.list'))
    return render_template(url + "delete.html", form=form, director=director)

filmsite/directors/templates/directors/all.html
{% extends "base.html" %}

{% block page_name %}Alle regisseurs{% endblock %}

{% block page %}

{% if current_user.is_authenticated %}
<a class="btn btn-primary" href="{{ url_for('directors.add') }}">
    Maak nieuwe regisseur aan
</a>
{% endif %}

{% for director in directors %}
<a href="{{ url_for('directors.show', director_id = director.id) }}">
    <h3>
        {{ director.first_name }} {{ director.last_name}}
    </h3>
</a>

{% endfor %}

{% endblock %}

filmsite/directors/templates/directors/create.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block page_name %} Maak nieuwe regisseur aan {% endblock %}
{% block page %}

    <h1>Voeg regisseur toe</h1>
    {{ wtf.quick_form(form, button_map={'submit': 'primary'}) }}

{% endblock %}

filmsite/directors/templates/directors/delete.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_name %}Verwijder directeur{% endblock %}

{% block page %}
<h3>Weet je zeker dat je deze directeur wilt verwijderen?</h3>

{{ wtf.quick_form(form, button_map={'submit': 'danger'}) }}
{% endblock %}

filmsite/directors/templates/directors/edit.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block page_name %} Maak nieuwe regisseur aan {% endblock %}
{% block page %}

    <h1>Bewerk regisseur</h1>
    {{ wtf.quick_form(form, button_map={'submit': 'primary'}) }}

{% endblock %}

filmsite/directors/templates/directors/view.html
{% extends "base.html" %}

{% block page_name %} Regisseur {{director.first_name}} {{ director.last_name}}{% endblock %}

{% block page %}

{% if current_user.is_authenticated %}
<a class="btn btn-primary" href="{{ url_for('directors.edit', director_id = director.id) }}">
    Bewerk regisseur
</a>

<a class="btn btn-danger" href="{{url_for('directors.delete', director_id = director.id)}}">Verwijder directeur</a>
{% endif %}
<h3>
    {{ director.first_name }} {{ director.last_name}}
</h3>

<h4>
    Films:
</h4>
<ul>
    {% for movie in director.movies %}
    <li>
        Regisseur van <a href="{{ url_for('movies.show', movie_id = movie.id) }}">{{movie.title}}</a>
            
    </li>
    {% endfor %}
</ul>

{% endblock %}